version: 1.0.0
server:
  port: 8181
spring:
  application:
    name: dragonfly-site #表示应用名称
  thymeleaf:
    prefix: classpath:/static/
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
  datasource:
      name: test
      url: jdbc:mysql://120.78.206.93:3306/dragonfly?useUnicode=true&characterEncoding=UTF8
      username: root
      password: dragonfly
      type: com.alibaba.druid.pool.DruidDataSource # 使用druid数据源
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml